type Asset = {
    _morphType: 'asset';
    id: string;
    project_id: string;
    user_id: string | null;
    name: string;
    thumbnail: string;
    thumbnail_route: string;
    versions_size: FileSize;
    exports_size: FileSize;
    annotation_attachments_size: FileSize;
    storage_size: FileSize;
    shareable_route: string | null;
    iteration: number;
    is_shared: boolean;
    is_downloadable_shared: boolean;
    is_versions_shared: boolean;
    is_materials_shared: boolean;
    is_pending: boolean;
    is_pending_version: boolean;
    is_approved: boolean;
    is_published: boolean;
    is_within_one_hour: boolean;
    failed_message: string | null;
    failed_at: string | null;
    created_at: string;
    updated_at: string;
    deleted_at: string | null;
    project?: Project;
    tags?: Tag[];
    user?: User;
    collections?: AssetCollection[];
    version?: AssetVersion;
    active_download?: Download;
    latest_review?: Review;
    member?: Member;
};

type AssetVersion = {
    _morphType: 'assetVersion';
    id: string;
    asset_id: string;
    user_id: string | null;
    name: string;
    thumbnail: string | null;
    thumbnail_route: string | null;
    state: AssetState;
    is_active: boolean;
    file: string;
    file_route: string;
    file_size: FileSize;
    total_size: FileSize;
    attachments_size: FileSize;
    faces_count: number | null;
    vertices_count: number | null;
    edges_count: number | null;
    triangles_count: number | null;
    iteration: number;
    source_file: string | null;
    source_file_route: string | null;
    set_origin_type: SetOriginType | null;
    set_origin_center: SetOriginCenter | null;
    is_setting_origin: boolean;
    use_compatibility_scaling: boolean;
    uv_unwrapped: UvUnwrapped;
    uv_islands: UvIslands;
    uv_islands_processed_at: string | null;
    glb_textures_extracted: GlbTexturesExtracted;
    source_files: string[] | null;
    attachments: Attachment[] | null;
    nodes: NodeItem[] | null;
    hidden_nodes: HiddenNodeItem[] | null;
    materials: AssetStoredMaterial[] | null;
    materials_map: Material[] | null;
    raw_materials_map: FortnitePropMaterial[] | null;
    scene: AssetSavedScene | null;
    quick_save: AssetSaveContent | null;
    active_save?: AssetSave;
    active_download?: Download;
    created_at: string;
    updated_at: string;
};
