type Copy = {
    _morphType: 'copy';
    id: string;
    user_id: string | null;
    source_id: string | null;
    source_type: string | null;
    target_id: string | null;
    target_type: string | null;
    collection_id: string | null;
    collection_type: string | null;
    output_id: string | null;
    output_type: string | null;
    status: 'processing' | 'completed' | 'failed';
    created_at: string;
    updated_at: string;
    user?: User;
    source?: Asset | UserAsset | null;
    target?: Project | User | null;
    collection?: AssetCollection | UserAssetCollection | null;
    output?: Asset | UserAsset | null;
};
