type IntractAsset = {
    _morphType: 'intractAsset';
    id: string;
    user_id: string | null;
    name: string;
    thumbnail: string;
    thumbnail_route: string;
    versions_size: FileSize;
    is_pending: boolean;
    is_pending_version: boolean;
    is_published: boolean;
    failed_message: string | null;
    failed_at: string | null;
    created_at: string;
    updated_at: string;
    deleted_at: string | null;
    user?: User;
    version?: IntractAssetVersion;
    iteration: undefined;
};

type IntractAssetVersion = {
    _morphType: 'intractAssetVersion';
    id: string;
    intract_asset_id: string;
    user_id: string | null;
    name: string;
    thumbnail: string | null;
    thumbnail_route: string | null;
    state: AssetState;
    is_active: boolean;
    file: string;
    file_route: string;
    file_size: FileSize;
    total_size: FileSize;
    attachments_size: FileSize;
    faces_count: number | null;
    vertices_count: number | null;
    edges_count: number | null;
    triangles_count: number | null;
    iteration: number;
    source_file: string | null;
    source_file_route: string | null;
    set_origin_type: SetOriginType | null;
    set_origin_center: SetOriginCenter | null;
    is_setting_origin: boolean;
    use_compatibility_scaling: boolean;
    uv_unwrapped: UvUnwrapped;
    uv_islands: UvIslands;
    uv_islands_processed_at: string | null;
    glb_textures_extracted: GlbTexturesExtracted;
    source_files: string[] | null;
    attachments: Attachment[] | null;
    nodes: NodeItem[] | null;
    hidden_nodes: HiddenNodeItem[] | null;
    materials: AssetStoredMaterial[] | null;
    materials_map: Material[] | null;
    raw_materials_map: FortnitePropMaterial[] | null;
    scene: AssetSavedScene | null;
    quick_save: null;
    active_save: undefined;
    active_download?: Download;
    created_at: string;
    updated_at: string;
};
