type UserLogin = {
    _morphType: 'userLogin';
    id: string;
    user_id: string;
    ip: string | null;
    platform: string | null;
    continent: string | null;
    continent_code: string | null;
    country: string | null;
    country_code: string | null;
    region: string | null;
    region_name: string | null;
    city: string | null;
    district: string | null;
    zip: string | null;
    lat: string | null;
    lon: string | null;
    timezone: string | null;
    currency: string | null;
    isp: string | null;
    org: string | null;
    as: string | null;
    mobile: boolean | null;
    proxy: boolean | null;
    hosting: boolean | null;
    created_at: string;
    updated_at: string;
    user?: User;
};
