FROM 573377737753.dkr.ecr.us-east-1.amazonaws.com/intract/nginx:latest

RUN mkdir -p /var/www/build
COPY . /var/www/build
WORKDIR /var/www/build

ENV NODE_OPTIONS="--max_old_space_size=8192"

RUN yarn
RUN yarn workspace @intractinc/base build
RUN yarn build

