apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nc-prod-crt
  namespace: nc-prod
spec:
  secretName: nc-prod-cert
  dnsNames:
    - nightscloak.com
    - www.nightscloak.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer