type ModelPortalSharedMode = 'asset' | 'presentation' | 'userAsset';

type ModelPortalProps = {
    children?: ReactNode;
    asset: Asset | UserAsset | IntractAsset;
    setAssetOverride?: Dispatch<SetStateAction<Asset | UserAsset | IntractAsset | undefined>>;
    fetchAsset?: () => void;
    updateConfig?: (config: AssetVersion | UserAssetVersion | IntractAssetVersion) => void;
    parent: MutableRefObject<HTMLDivElement>;
    canvas: MutableRefObject<HTMLCanvasElement>;
    forceMode?: Mode;
    communityReference?: UserAssetCollection | Project;
    member?: Member | AssetMember;
    admin?: boolean;
    sharedMode?: ModelPortalSharedMode;
    presentation?: AssetPresentation;
    sharedCode?: string;
    guestSession?: string | null;
    previewVersion?: AssetVersion;
    setPreviewVersion?: Dispatch<SetStateAction<AssetVersion | undefined>>;
    previewSavepoint?: AssetSave;
    setPreviewSavepoint?: Dispatch<SetStateAction<AssetSave | undefined>>;
    sharedModelLoadSaveAction?: SharedModelSaveAction;
    setSharedModelLoadSaveAction?: Dispatch<SetStateAction<SharedModelSaveAction>>;
};

type ModelPortalContextProps = {
    initialize: () => void;
    isInitialized: boolean;
    reset: (options?: ResetOptions) => void;
    resetting: ResetOptions | null;
    debug: boolean;
    admin?: boolean;
    sharedMode?: ModelPortalSharedMode;
    presentation?: AssetPresentation;
    sharedCode?: string;
    guestSession?: string | null;
    setDebug: Dispatch<SetStateAction<boolean>>;
    asset: Asset | UserAsset | IntractAsset;
    setAssetOverride?: Dispatch<SetStateAction<Asset | UserAsset | IntractAsset | undefined>>;
    member?: Member | AssetMember;
    communityReference?: UserAssetCollection | Project;
    fetchAsset: () => void;
    updateConfig: (config: AssetVersion | UserAssetVersion | IntractAssetVersion) => void;
    parent: RefObject<HTMLDivElement>;
    canvas: RefObject<HTMLCanvasElement>;
    engine: { current: Engine };
    assetLoadState: AssetLoadedState;
    updateAssetLoadState: (state: UpdateAssetLoadedState) => void;
    currentSelectionId: string | null;
    setCurrentSelectionId: Dispatch<SetStateAction<string | null>>;
    undoCount: number;
    setUndoCount: Dispatch<SetStateAction<number>>;
    actionTimes: ActionTimes;
    updateActionTimes: (times: UpdateActionTimes) => void;
    loadingOverlay: LoadingOverlay;
    setLoadingOverlay: Dispatch<SetStateAction<LoadingOverlay>>;
    activeTool: EditorMenuSections;
    setActiveTool: Dispatch<SetStateAction<EditorMenuSections>>;
    activeSpeedDialTool: ToolsSpeedDialMenuSections;
    setActiveSpeedDialTool: Dispatch<SetStateAction<ToolsSpeedDialMenuSections>>;
    activeApplicator: ActiveApplicator;
    setActiveApplicator: Dispatch<SetStateAction<ActiveApplicator>>;
    mode: Mode;
    setCurrentMode: (mode: Mode) => void;
    camera: Camera;
    setCurrentCamera: (camera: Camera) => void;
    isDialogOpen: boolean;
    setIsDialogOpen: Dispatch<SetStateAction<boolean>>;
    showAnnotations: boolean;
    setShowAnnotations: Dispatch<SetStateAction<boolean>>;
    showReviews: boolean;
    setShowReviews: Dispatch<SetStateAction<boolean>>;
    showPresentation: boolean;
    setShowPresentation: Dispatch<SetStateAction<boolean>>;
    showMaterials: boolean;
    setShowMaterials: Dispatch<SetStateAction<boolean>>;
    reviewId: string | null;
    setReviewId: Dispatch<SetStateAction<string | null>>;
    socket: PresenceChannel | null;
    users: User[];
    previewVersion?: AssetVersion;
    setPreviewVersion?: Dispatch<SetStateAction<AssetVersion | undefined>>;
    previewSavepoint?: AssetSave;
    setPreviewSavepoint?: Dispatch<SetStateAction<AssetSave | undefined>>;
    sharedModelLoadSaveAction?: SharedModelSaveAction;
    setSharedModelLoadSaveAction?: Dispatch<SetStateAction<SharedModelSaveAction>>;
    materialAndNodeTinkerOverride: boolean;
};
