on:
  push:
    tags:
      - v*.*.*

env:
  AWS_REGION: "us-east-1"
  REGISTRY_URI: 573377737753.dkr.ecr.us-east-1.amazonaws.com
  REGISTRY_NAME: intract
  NAMESPACE: prod
  APP_NAME: admin
  KUBECTL_PATH: ./docker/admin.prod.yaml
  ENVIRONMENT: prod
  NODE_VERSION: 23.x
  NODE_OPTIONS: "--max_old_space_size=6144"
  VITE_APP: "admin"
  VITE_SCHEMA: "https"
  VITE_URI: "admin.intract.com"
  VITE_PREFIX: "api/v1"
  VITE_CLIENT_SECRET: "drmBymjW550dQl2QcMtZbRDHjgWCEx4AHfelVuKY"
  VITE_CLIENT_ID: "96cfd5b7-aad5-4b20-a8dd-3e04829dc97f"
  VITE_STRIPE_PK: "pk_live_51OK4TCLpmBnJBh8WqSpjtzWNkVHrgS9zyYb6YIwjcd9q3QgPLvz8Thfomrngyqw9U7AMxXrL0v2Cl666O1ZdTF0j00FKW9GQf0"
  VITE_PUSHER_APP_KEY: "fRjsvk6EPrRBZkwbt3nqze"
  VITE_PUSHER_APP_WSS_PORT: "443"
  VITE_PUSHER_APP_WS_PORT: "80"
  VITE_PUSHER_APP_PATH: "/socket"
  VITE_DEPLOY_ENV: "production"
  VITE_SENTRY: "true"
  VITE_SENTRY_TELEMETRY: "true"
  VITE_SENTRY_SOURCE_MAPS: "true"
  VITE_REG_OPEN: "true"
  VITE_AUTH_FLOW: "auth"
  VITE_ANALYTICS_ID: "G-NR826HGLJP"

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest-l
    strategy:
      matrix:
        php: [ 8.3.9 ]
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      # Set platform as env for use later
      - name: Prepare Platform
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Clone Repo
        uses: actions/checkout@main
        with:
          submodules: 'true'
          token: ${{ secrets.CICD_PAT }}

      # Setup Yarn
      - name: Yarn Setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'

      # Assume AWS Role and set kubectl
      - name: Configure Aws Creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::573377737753:role/GithubECR
          role-session-name: GitHub_AWS_ODIC
          aws-region: ${{ env.AWS_REGION }}

      # Assume AWS Role and set Kubectl
      - name: STS GetCallerIdentity
        run: |
          aws sts get-caller-identity
          mkdir -p $HOME/.kube
          echo "$KUBE_CONFIG_DATA" | base64 -d > $HOME/.kube/config
          aws eks update-kubeconfig --name intract

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Setup Sentry, only for x86
      - name: Sentry Release Management
        uses: getsentry/action-release@v1
        if: ${{ env.PLATFORM_PAIR == 'linux-amd64' }}
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: ${{ env.ENVIRONMENT }}
          ignore_missing: true

      # Install Deps
      - name: Install Dependencies
        run: yarn

      # Build App
      - name: Yarn Build amd64
        if: ${{ env.PLATFORM_PAIR == 'linux-amd64' }}
        run: yarn build:app
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      # Build App for non k8s platform (local dev testing)
      - name: Yarn Build arm64
        if: ${{ env.PLATFORM_PAIR == 'linux-arm64' }}
        run: yarn build:app

      # Set Docker image tag for build
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: |
            latest=true
          tags: |
            type=raw,value=${{ env.ENVIRONMENT }}-${{ github.sha }}
          images: ${{ env.REGISTRY_URI }}/${{ env.REGISTRY_NAME }}/${{ env.APP_NAME }}

      - name: Setup Qemu for multiplatform
        uses: docker/setup-qemu-action@v3

      # Setup Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Container build and push to a Container Registry (ACR)
      - name: Build and Push
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ env.REGISTRY_URI }}/${{ env.REGISTRY_NAME }}/${{ env.APP_NAME }},push-by-digest=true,name-canonical=true,push=true
          cache-from: type=registry,ref=${{ env.REGISTRY_URI }}/${{ env.REGISTRY_NAME }}/${{ env.APP_NAME }}:cache-${{ env.ENVIRONMENT }}-${{ env.PLATFORM_PAIR }}
          cache-to: type=registry,image-manifest=true,oci-mediaTypes=true,ref=${{ env.REGISTRY_URI }}/${{ env.REGISTRY_NAME }}/${{ env.APP_NAME }}:cache-${{ env.ENVIRONMENT }}-${{ env.PLATFORM_PAIR }},mode=max
          file: ./docker/Dockerfile

      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    runs-on: ubuntu-latest-l
    needs: [ build ]
    steps:
      # Get previous data
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-*
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: |
            latest=true
          tags: |
            type=raw,value=${{ env.ENVIRONMENT }}-${{ github.sha }}
          images: ${{ env.REGISTRY_URI }}/${{ env.REGISTRY_NAME }}/${{ env.APP_NAME }}

      # Set AWS Credentials
      - name: Configure Aws Creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::573377737753:role/GithubECR
          role-session-name: GitHub_AWS_ODIC
          aws-region: ${{ env.AWS_REGION }}

      - name: STS GetCallerIdentity
        run: |
          aws sts get-caller-identity

      # Connect to Container Registry
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REGISTRY_URI }}/${{ env.REGISTRY_NAME }}/${{ env.APP_NAME }}@sha256:%s ' *)
      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY_URI }}/${{ env.REGISTRY_NAME }}/${{ env.APP_NAME }}:${{ steps.meta.outputs.version }}

  deploy:
    runs-on: ubuntu-latest-l
    needs: [ merge ]
    steps:
      - name: Clone Repo
        uses: actions/checkout@main
        with:
          submodules: 'true'
          token: ${{ secrets.CICD_PAT }}

      # Assume AWS Role and set kubectl
      - name: Configure Aws Creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::573377737753:role/GithubECR
          role-session-name: GitHub_AWS_ODIC
          aws-region: ${{ env.AWS_REGION }}

      # Assume AWS Role and set Kubectl
      - name: STS GetCallerIdentity
        run: |
          aws sts get-caller-identity
          mkdir -p $HOME/.kube
          echo "$KUBE_CONFIG_DATA" | base64 -d > $HOME/.kube/config
          aws eks update-kubeconfig --name intract

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      #ENV Subst for deployment
      - name: Generate Kubectl Deployment File
        env:
          COMMIT: ${{ github.sha }}
        run: |
          set -e
          envsubst < ${{ env.KUBECTL_PATH }} > ./docker/deploy.yaml

      # Deploy app to AKS
      - name: Deploy to AKS
        uses: azure/k8s-deploy@v1
        with:
          manifests: |
            docker/deploy.yaml
          images: |
            ${{ env.REGISTRY_URI }}/${{ env.REGISTRY_NAME }}/${{ env.APP_NAME }}:${{ env.ENVIRONMENT }}-${{ github.sha }}
          namespace: ${{ env.NAMESPACE }}